using System.ComponentModel;

namespace NfaLoader.Localization;

/// <summary>
/// Entry object for XAML bindings. XAML writes {x:Bind Strings.Get('Key'), Mode=OneWay}, and the function binding generated by compiled x:Bind calls <see cref="Get"/>.
/// It holds no language state of its own: key lookups are forwarded to <see cref="Loc.T"/>.
///
/// Live switching: this object is a singleton whose identity never changes, so its own PropertyChanged cannot make x:Bind re-evaluate;
/// instead the host page raises PropertyChanged for its "Strings" property on <see cref="Loc.LanguageChanged"/>,
/// x:Bind reads Strings again → calls Get('Key') again and gets the text in the new language. <see cref="RaiseAllChanged"/> is kept only for symmetry.
/// </summary>
internal sealed partial class LocalizedStrings : INotifyPropertyChanged
{
    public event PropertyChangedEventHandler? PropertyChanged;

    /// <summary>Gets the text for a key in the current language. Called by the x:Bind function binding: {x:Bind Strings.Get('Key'), Mode=OneWay}.</summary>
    public string Get(string key) => Loc.T(key);

    /// <summary>Broadcasts "everything changed", for future cases that bind directly to this object's properties; pages today go through the host's PropertyChanged("Strings").</summary>
    internal void RaiseAllChanged() => PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(string.Empty));
}
